name: Documentation generation

on:
  push:
    branches:
      - master
  repository_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.action == 'docs_build'
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 12.20.0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Clone guide repo
        run: git clone https://github.com/Discordoo/discordoo-guide docs

      - name: Clone collection repo
        run: git clone https://github.com/Discordoo/collection __collection__

      - name: Run collection docs generation
        run: npm run docs:collection

      - name: Install ddoo required packages
        run: npm ci

      - name: Run ddoo docs generation
        run: npm run docs

      - name: Install mkdocs required packages
        run: pip install -r ./docs/requirements.txt

      - name: Run mkdocs build
        working-directory: ./docs
        run: mkdocs build

      - name: Deploy
        uses: 'JamesIves/github-pages-deploy-action@4.1.3'
        with:
          branch: gh-pages
          folder: docs/site
