name: Documentation generation

on:
  - push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Install packages etc
        run: |
          npm ci
          npm run docs
      - name: Deploy
        uses: 'JamesIves/github-pages-deploy-action@4.1.3'
        with:
          branch: gh-pages
          folder: docs
